'use client';

import { useEffect, useState } from 'react';
import { ArrowDownTrayIcon, BellAlertIcon } from '@heroicons/react/24/outline';
import { calendarIcs, DEMO_TODAY, daysUntil, effectiveStatus, type AlertKind, type AppAlert } from '@/lib/alerts';
import { formatDateEs } from '@/lib/date';
import type { DemoState } from '@/lib/demo-store';
import type { Section } from './sidebar';

type Mutate = (fn: (state: DemoState) => DemoState) => void;
const Panel = ({ title, subtitle, children, action }: { title: string; subtitle: string; children: React.ReactNode; action?: React.ReactNode }) => <section className="rounded-2xl border border-white/10 bg-petroleum-900 p-5 shadow-panel"><div className="mb-5 flex flex-wrap items-start justify-between gap-4"><div><h3 className="font-bold text-white">{title}</h3><p className="mt-1 text-xs text-slate-400">{subtitle}</p></div>{action}</div>{children}</section>;
const Empty = ({ children }: { children: React.ReactNode }) => <div className="rounded-xl border border-dashed border-white/15 p-10 text-center text-sm text-slate-400">{children}</div>;
const dateEs = (value: string) => formatDateEs(value);
const supplierName = (state: DemoState, id: string) => state.suppliers.find((item) => item.id === id)?.name || 'Sin proveedor';
const Badge = ({ value }: { value: string }) => <span className={/activa|Alta/.test(value) ? 'badge-red' : /leída|Media/.test(value) ? 'badge-green' : 'badge-amber'}>{value}</span>;

export function AlertExpiries({ state, update, notify, onNavigate }: { state: DemoState; update: Mutate; notify: (message: string) => void; onNavigate: (section: Section) => void }) {
  const demo = () => { const source = state.expiries[0]; if (!source) return notify('No hay vencimientos para preparar la demo'); const next = { ...source, id: `${source.id}-demo`, date: DEMO_TODAY, lot: `${source.lot}-DEMO` }; update((current) => ({ ...current, expiries: [...current.expiries.filter((item) => item.id !== next.id), next] })); notify('Alerta demo cargada'); };
  return <Panel title="Vencimientos" subtitle={`Fecha de referencia: ${dateEs(DEMO_TODAY)} · reglas exactas: 3, 2, 1 días y día del vencimiento`} action={<div className="flex flex-wrap gap-2"><button type="button" className="button-secondary" onClick={demo}>Cargar alerta demo</button><button type="button" className="button-secondary" onClick={() => onNavigate('Agenda')}>Ver Agenda</button></div>}>{state.expiries.length ? <div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Fecha</th><th>Producto</th><th>Proveedor</th><th>Lote</th><th>Cantidad</th><th>Prioridad</th></tr></thead><tbody>{state.expiries.map((expiry) => { const remaining = daysUntil(expiry.date); return <tr key={expiry.id}><td>{dateEs(expiry.date)}</td><td>{state.products.find((item) => item.id === expiry.productId)?.name || 'Producto eliminado'}</td><td>{supplierName(state, expiry.supplierId)}</td><td>{expiry.lot}</td><td>{expiry.quantity}</td><td><Badge value={remaining <= 0 ? 'Alta' : 'Media'} /></td></tr>; })}</tbody></table></div> : <Empty>No hay vencimientos.</Empty>}</Panel>;
}

function AlertCard({ alert, state, update, onNavigate }: { alert: AppAlert; state: DemoState; update: Mutate; onNavigate: (section: Section) => void }) { const status = effectiveStatus(alert); const change = (next: 'leída' | 'descartada') => update((current) => ({ ...current, alerts: current.alerts.map((item) => item.id === alert.id ? { ...item, status: next } : item) })); return <div className="rounded-xl border border-white/10 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="text-sm font-bold text-white">{alert.title}</span><Badge value={status} /></div><p className="mt-1 text-xs text-slate-400">{dateEs(alert.referenceDate)} · {alert.detail}</p></div><div className="flex flex-wrap gap-2"><button type="button" className="button-primary" onClick={() => onNavigate(alert.kind === 'vencimiento' ? 'Vencimientos' : 'Recepcion')}>Abrir registro</button>{status !== 'leída' && status !== 'descartada' && <button type="button" className="button-secondary" onClick={() => change('leída')}>Marcar leída</button>}{status !== 'descartada' && <button type="button" className="button-secondary" onClick={() => change('descartada')}>Descartar</button>}</div></div></div>; }

export function AlertAgenda({ state, update, notify, onNavigate }: { state: DemoState; update: Mutate; notify: (message: string) => void; onNavigate: (section: Section) => void }) { const [kind, setKind] = useState<'todas' | AlertKind>('todas'); const rows = state.alerts.filter((alert) => kind === 'todas' || alert.kind === kind); const exportIcs = () => { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([calendarIcs(rows)], { type: 'text/calendar;charset=utf-8' })); link.download = 'zavryon-alertas.ics'; link.click(); notify('ICS descargado con VALARM.'); }; return <Panel title="Agenda / Calendario" subtitle="Vencimientos y entregas; exporta para usarlo fuera de la app" action={<div className="flex flex-wrap gap-2"><select aria-label="Filtrar tipo de alerta" className="field" value={kind} onChange={(event) => setKind(event.target.value as typeof kind)}><option value="todas">Todas</option><option value="vencimiento">Vencimientos</option><option value="entrega">Entregas</option></select><button type="button" className="button-primary" onClick={exportIcs}><ArrowDownTrayIcon className="h-4 w-4" /> Exportar .ics</button></div>}>{rows.length ? <div className="space-y-3">{rows.sort((a, b) => a.referenceDate.localeCompare(b.referenceDate)).map((alert) => <AlertCard key={alert.id} alert={alert} state={state} update={update} onNavigate={onNavigate} />)}</div> : <Empty>No hay alertas.</Empty>}</Panel>; }

export function Notifications({ state, update, notify, onNavigate }: { state: DemoState; update: Mutate; notify: (message: string) => void; onNavigate: (section: Section) => void }) {
  const [permission, setPermission] = useState<NotificationPermission | 'no disponible'>('no disponible');
  const supported = typeof window !== 'undefined' && 'Notification' in window;
  useEffect(() => { setPermission(supported ? Notification.permission : 'no disponible'); }, [supported]);
  const enable = async () => { if (!supported) return notify('No disponible: usa alertas internas o exporta .ics.'); const result = permission === 'default' ? await Notification.requestPermission() : permission; setPermission(result); if (result === 'granted') update((current) => ({ ...current, alertPreferences: { ...current.alertPreferences, browser: true } })); notify(result === 'granted' ? 'Permiso concedido' : 'Permiso no concedido; se mantienen alertas internas y exportación ICS.'); };
  const toggle = (field: 'expiries' | 'deliveries') => update((current) => ({ ...current, alertPreferences: { ...current.alertPreferences, [field]: !current.alertPreferences[field] } }));
  const permissionLabel = !supported ? 'No disponible' : permission === 'granted' ? 'Permiso concedido' : permission === 'denied' ? 'Permiso denegado' : 'Compatible, permiso pendiente';
  return <Panel title="Centro de notificaciones" subtitle={`${state.alerts.filter((alert) => effectiveStatus(alert) === 'activa').length} alerta(s) activa(s) · reglas 3/2/1/0 días y pedidos 1/0 días`} action={<div className="flex flex-wrap gap-2"><button type="button" className="button-primary" onClick={enable}><BellAlertIcon className="h-4 w-4" /> Solicitar permiso</button><button type="button" className="button-secondary" onClick={() => onNavigate('Agenda')}>Abrir calendario</button></div>}><div className="mb-5 rounded-xl border border-white/10 p-4 text-sm text-slate-300"><strong className="text-white">Estado Notification API:</strong> {permissionLabel}. El service worker ofrece soporte local cuando el navegador lo permite. Para funcionar con la app cerrada en todos los dispositivos se necesita Web Push, suscripción, VAPID y backend/job; queda pendiente para Supabase Edge Functions.</div><div className="mb-5 grid gap-3 sm:grid-cols-2"><label className="flex min-h-12 items-center justify-between rounded-xl border border-white/10 px-4 text-sm text-slate-300">Alertas de vencimientos <input aria-label="Activar alertas de vencimientos" type="checkbox" checked={state.alertPreferences.expiries} onChange={() => toggle('expiries')} /></label><label className="flex min-h-12 items-center justify-between rounded-xl border border-white/10 px-4 text-sm text-slate-300">Alertas de entregas <input aria-label="Activar alertas de entregas" type="checkbox" checked={state.alertPreferences.deliveries} onChange={() => toggle('deliveries')} /></label></div><p className="text-xs text-slate-400">Si el navegador no es compatible o deniega el permiso, las alertas permanecen dentro de la app y puedes exportarlas como calendario ICS.</p></Panel>;
}
