'use client';

import { useEffect, useMemo, useState } from 'react';
import { PlusIcon, TrashIcon, XMarkIcon } from '@heroicons/react/24/outline';
import type { DemoState } from '@/lib/demo-store';
import type { Order, OrderLine } from '@/lib/mock-data';
import { money, toNumber } from '@/lib/format';

type Mutate = (fn: (state: DemoState) => DemoState) => void;

export function OrderEditor({ order, state, update, onClose }: { order: Order; state: DemoState; update: Mutate; onClose: () => void }) {
  const [draft, setDraft] = useState(order);
  const [productId, setProductId] = useState('');
  const [message, setMessage] = useState('');
  const products = useMemo(() => state.products.filter((product) => product.active), [state.products]);
  useEffect(() => { if (!productId) setProductId(products[0]?.id || ''); }, [productId, products]);
  const setLine = (id: string, patch: Partial<OrderLine>) => setDraft((current) => ({ ...current, lines: current.lines.map((line) => line.id === id ? { ...line, ...patch } : line) }));
  const addLine = () => { const product = products.find((item) => item.id === productId); if (!product) return; const existing = draft.lines.find((line) => line.productId === product.id); if (existing) return setLine(existing.id, { quantity: existing.quantity + 1 }); const supplierPrice = state.supplierProducts.find((item) => item.productId === product.id && item.supplierId === draft.supplierId)?.price || 0; setDraft((current) => ({ ...current, lines: [...current.lines, { id: `ol-${Date.now()}`, productId: product.id, quantity: 1, price: supplierPrice }] })); };
  const save = () => { if (!draft.supplierId || !draft.responsible || !draft.lines.length || draft.lines.some((line) => line.quantity < 1 || line.price < 0)) return setMessage('Completa proveedor, responsable y líneas válidas.'); update((current) => ({ ...current, orders: current.orders.map((item) => item.id === draft.id ? draft : item) })); setMessage('Pedido guardado'); window.setTimeout(onClose, 250); };
  return <div className="drawer-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside className="order-drawer" role="dialog" aria-modal="true" aria-labelledby="order-editor-title"><div className="flex items-start justify-between gap-4 border-b border-white/10 pb-4"><div><h2 id="order-editor-title" className="text-lg font-bold text-white">Editar pedido {draft.id}</h2><p className="mt-1 text-xs text-slate-400">Metadatos, líneas y valores editables. Recepción y pagos se conservan.</p></div><button type="button" className="icon-button" aria-label="Cerrar editor de pedido" onClick={onClose}><XMarkIcon className="h-6 w-6" /></button></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-300">Proveedor<select className="field mt-1 w-full" value={draft.supplierId} onChange={(event) => setDraft({ ...draft, supplierId: event.target.value })}>{state.suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></label><label className="text-xs font-semibold text-slate-300">Responsable<input className="field mt-1 w-full" value={draft.responsible} onChange={(event) => setDraft({ ...draft, responsible: event.target.value })} /></label><label className="text-xs font-semibold text-slate-300">Solicitante<input className="field mt-1 w-full" value={draft.requester || ''} onChange={(event) => setDraft({ ...draft, requester: event.target.value })} /></label><label className="text-xs font-semibold text-slate-300">Entrega prevista<input className="field mt-1 w-full" type="date" value={draft.expectedDate} onChange={(event) => setDraft({ ...draft, expectedDate: event.target.value })} /></label><label className="text-xs font-semibold text-slate-300 sm:col-span-2">Notas<textarea className="field mt-1 min-h-20 w-full" value={draft.notes} onChange={(event) => setDraft({ ...draft, notes: event.target.value })} /></label></div>
    <div className="mt-6 rounded-xl border border-cyan-300/20 bg-ink/40 p-4"><div className="flex flex-wrap items-end gap-2"><label className="min-w-0 flex-1 text-xs font-semibold text-slate-300">Agregar producto<select className="field mt-1 w-full" value={productId} onChange={(event) => setProductId(event.target.value)}>{products.map((product) => <option key={product.id} value={product.id}>{product.name} · {product.sku}</option>)}</select></label><button type="button" className="button-primary" onClick={addLine}><PlusIcon className="h-4 w-4" /> Agregar</button></div></div>
    <div className="mt-5 space-y-3">{draft.lines.map((line) => { const product = products.find((item) => item.id === line.productId); return <div key={line.id} className="grid gap-3 rounded-xl border border-white/10 p-4 sm:grid-cols-[minmax(0,1fr)_100px_140px_auto] sm:items-end"><div className="text-sm font-semibold text-white">{product?.name || 'Producto eliminado'}<span className="mt-1 block text-xs font-normal text-slate-500">SKU: {product?.sku || 'Sin SKU'}</span></div><label className="text-xs font-semibold text-slate-300">Cantidad<input className="field mt-1 w-full" type="number" min="1" value={line.quantity} onChange={(event) => setLine(line.id, { quantity: toNumber(event.target.value, 1) })} /></label><label className="text-xs font-semibold text-slate-300">Precio<input className="field mt-1 w-full" type="number" min="0" step="0.01" value={line.price} onChange={(event) => setLine(line.id, { price: toNumber(event.target.value) })} /></label><button type="button" className="button-danger" aria-label={`Quitar ${product?.name || 'línea'}`} onClick={() => setDraft((current) => ({ ...current, lines: current.lines.filter((item) => item.id !== line.id) }))}><TrashIcon className="h-4 w-4" /> Quitar</button></div>; })}</div>
    <div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4"><div className="text-xl font-bold text-white">Total {money(draft.lines.reduce((sum, line) => sum + line.quantity * line.price, 0))}</div><div className="flex gap-2"><button type="button" className="button-secondary" onClick={onClose}>Cerrar</button><button type="button" className="button-primary" onClick={save}>Guardar cambios</button></div></div>{message && <p role="status" className="mt-3 text-sm text-cyan-200">{message}</p>}</aside></div>;
}
