import type { Evidence, ExtractionResult, FieldResult, SourceCandidate, SourceCandidateFields } from './mock-data';
import { dedupeCandidates, normalizeSourceCandidate, SOURCE_LIMITS } from './source-validation';
export const EXTRACTOR_VERSION = 'sources-1.0';
const evidence = (label: string, excerpt: string, source: string, locator?: string): Evidence => ({ label, excerpt: excerpt.slice(0, 300), source, locator });
const field = <T>(value: T, ev: Evidence[], provenance: string, confidence = ev.length ? 0.8 : 0): FieldResult<T> => ({ value, evidence: ev, provenance, confidence, needsReview: confidence < 0.7 || !ev.length });
const numberValue = (raw: string) => { const clean = raw.replace(/[^\d.,-]/g, ''); if (clean.includes(',') && clean.includes('.')) return Number(clean.lastIndexOf(',') > clean.lastIndexOf('.') ? clean.replace(/\./g, '').replace(',', '.') : clean.replace(/,/g, '')); if (clean.includes(',')) return Number(clean.replace(',', '.')); const parts = clean.split('.'); return parts.length > 1 && parts[parts.length - 1].length === 3 ? Number(parts.join('')) : Number(clean); };
const money = (text: string) => { const match = text.match(/(?:ARS|USD|EUR|\$)\s*([\d.,]+)/i); return match ? { value: numberValue(match[1]), currency: /USD/i.test(match[0]) ? 'USD' : /EUR/i.test(match[0]) ? 'EUR' : 'ARS', raw: match[0] } : null; };
function makeCandidate(id: string, name: string, sku: string, price: { value: number; currency: string; raw: string } | null, ev: Evidence, imageUrl = ''): SourceCandidate { const fields: Partial<SourceCandidateFields> = { name: field(name, [ev], 'visible document'), ...(sku ? { sku: field(sku, [ev], 'visible document') } : {}), ...(price ? { price: field(price.value, [ev], 'visible document') } : {}), ...(imageUrl ? { image: field(imageUrl, [ev], 'JSON-LD/meta') } : {}) }; return normalizeSourceCandidate({ id, name, sku, brand: '', unit: '', category: '', price: price?.value || 0, currency: price?.currency || 'ARS', availability: '', expiry: '', imageUrl, fields: fields as SourceCandidateFields, confidence: Math.min(...Object.values(fields).map((item) => item!.confidence)), reviewState: 'pending', extractorVersion: EXTRACTOR_VERSION, status: 'Pendiente', notes: 'Sugerencia con evidencia; requiere revisión humana.' }); }
export function extractHtml(input: string, sourceId: string): ExtractionResult { const doc = new DOMParser().parseFromString(input.slice(0, SOURCE_LIMITS.maxText), 'text/html'); const candidates: SourceCandidate[] = []; const scripts = Array.from(doc.querySelectorAll('script[type="application/ld+json"]')); scripts.forEach((script, index) => { try { const value = JSON.parse(script.textContent || ''); const values = Array.isArray(value) ? value : [value, ...(Array.isArray(value?.['@graph']) ? value['@graph'] : [])]; values.filter((item) => item && (/product/i.test(item['@type'] || '') || item.name)).forEach((item, productIndex) => { const name = String(item.name || '').trim(); if (!name) return; const offer = Array.isArray(item.offers) ? item.offers[0] : item.offers || {}; const price = offer.price ? { value: Number(offer.price), currency: String(offer.priceCurrency || 'ARS'), raw: String(offer.price) } : null; const ev = evidence('JSON-LD', JSON.stringify(item), `script[type="application/ld+json"]`, `${index}:${productIndex}`); candidates.push(makeCandidate(`${sourceId}-jsonld-${index}-${productIndex}`, name, String(item.sku || item.mpn || ''), price, ev, typeof item.image === 'string' ? item.image : '')); }); } catch { /* Ignore malformed JSON-LD and continue with visible signals. */ } });
  doc.querySelectorAll('table').forEach((table, tableIndex) => { Array.from(table.querySelectorAll('tr')).slice(1, SOURCE_LIMITS.maxCandidates).forEach((row, rowIndex) => { const cells = Array.from(row.querySelectorAll('th,td')).map((cell) => cell.textContent?.replace(/\s+/g, ' ').trim() || ''); if (!cells[0]) return; const price = money(cells.join(' ')); const ev = evidence('Tabla visible', cells.join(' | '), 'HTML table', `${tableIndex}:${rowIndex}`); candidates.push(makeCandidate(`${sourceId}-table-${tableIndex}-${rowIndex}`, cells[0], cells.find((cell) => /\b[A-Z]{2,}[-_]?[A-Z0-9-]{2,}\b/.test(cell))?.match(/\b[A-Z]{2,}[-_]?[A-Z0-9-]{2,}\b/)?.[0] || '', price, ev)); }); });
  if (!candidates.length) doc.querySelectorAll('meta[property="og:title"],meta[name="twitter:title"]').forEach((meta, index) => { const name = meta.getAttribute('content')?.trim(); if (name) candidates.push(makeCandidate(`${sourceId}-meta-${index}`, name, '', null, evidence('Meta', name, 'HTML meta'))); });
  const result = { status: candidates.length ? 'ok' as const : 'manual_review' as const, candidates: dedupeCandidates(candidates).slice(0, SOURCE_LIMITS.maxCandidates), warnings: candidates.length ? [] : ['No se encontraron señales estructuradas visibles; agrega o revisa candidatos manualmente.'], extractorVersion: EXTRACTOR_VERSION }; return result;
}
export function extractText(text: string, sourceId: string): ExtractionResult { const candidates = text.slice(0, SOURCE_LIMITS.maxText).split(/\r?\n/).map((line, index) => line.trim()).filter(Boolean).flatMap((line, index) => { const price = money(line); const sku = line.match(/\b[A-Z]{2,}[-_]?[A-Z0-9-]{2,}\b/)?.[0] || ''; return price || sku ? [makeCandidate(`${sourceId}-text-${index}`, line.replace(price?.raw || '', '').replace(sku, '').trim() || `Candidato ${index + 1}`, sku, price, evidence('Texto PDF', line, 'PDF text layer', String(index)))] : []; }).slice(0, SOURCE_LIMITS.maxCandidates); return { status: candidates.length ? 'ok' : 'manual_review', candidates: dedupeCandidates(candidates), warnings: candidates.length ? [] : ['El documento tiene texto, pero no señales de producto estructuradas.'], extractorVersion: EXTRACTOR_VERSION }; }
